name: CI SonarCloud and Snyk Scan
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  sonarscan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sonarqube Scan
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=notification-service-pipelines
            -Dsonar.organization=muhammedsinanust
            -Dsonar.sources=.

      - name: Sonarqube Quality Gate Check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Sonarqube Report
        uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        

    #   - name: Snyk Scan
    #     uses: snyk/actions@master
    #     env:
    #       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #     with:
    #       args: test --all-projects --severity-threshold=high

      - name: Fail Email Notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: CI Pipeline Failure Notification
          body: The CI pipeline for the notification-service-pipelines repository has failed. Please check the SonarCloud and Snyk reports for details. Best regards, Your CI Pipeline
          to: ${{ secrets.RECIVER_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}
    
      - name: Email Notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: CI Pipeline Notification
          body: The CI pipeline for the notification-service-pipelines repository has completed successfully.
           Please check the SonarCloud and Snyk reports for details.
           Best regards,
           Your CI Pipeline
          to: ${{ secrets.RECIVER_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}