# name: CI SonarCloud and Snyk Scan
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
# jobs:
#   sonarscan:
#     name: SonarCloud Scan
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'

#       - name: Install Dependencies
#         run: npm install --ignore-scripts

#       - name: Run Tests and Generate Coverage
#         run: npm test

#       - name: SonarQube Scan
#         uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         with:
#           args: >
#             -Dsonar.projectKey=notification-service-pipelines
#             -Dsonar.organization=muhammedsinanust
#             -Dsonar.sources=.
#             -Dsonar.exclusions=node_modules/**,coverage/**,**/*.test.js
#             -Dsonar.coverage.exclusions=server.js
#             -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
#             -Dsonar.host.url=https://sonarcloud.io

#       - name: SonarQube Quality Gate check
#         id: sonarqube-quality-gate-check  
#         uses: sonarsource/sonarqube-quality-gate-action@d304d050d930b02a896b0f85935344f023928496
#         with:
#           scanMetadataReportFile: .scannerwork/report-task.txt
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#   snykscan:
#     name: Snyk Scan
#     needs: sonarscan
#     runs-on: ubuntu-latest
#     steps:          
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'

#       - name: Install Dependencies
#         run: npm ci --ignore-scripts
    
#       - name: Snyk Test
#         uses: snyk/actions/node@master
#         env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#         with:
#           args: --all-projects --severity-threshold=high --org=muhammedsinanust

#       - name: Snyk Monitor
#         uses: snyk/actions/node@master
#         env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#         with:
#           command: monitor
#           args: --all-projects --org=muhammedsinanust

#   mailnotification:    
#     name: Email Notification
#     needs: [sonarscan, snykscan]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Fail Email Notification
#         if: failure()
#         uses: dawidd6/action-send-mail@v3
#         with:
#           server_address: smtp.gmail.com
#           server_port: 465
#           username: ${{ secrets.EMAIL_USERNAME }}
#           password: ${{ secrets.EMAIL_PASSWORD }}
#           subject: CI Pipeline Failure Notification
#           body: The CI pipeline for the notification-service-pipelines repository has failed. with "${{ github.event.head_commit.message }}" Please check the SonarCloud and Snyk reports for details. Best regards, Your CI Pipeline
#           to: ${{ secrets.RECIVER_EMAIL }}
#           from: ${{ secrets.EMAIL_USERNAME }}
    
#       - name: Email Notification
#         if: success()
#         uses: dawidd6/action-send-mail@v3
#         with:
#           server_address: smtp.gmail.com
#           server_port: 465
#           username: ${{ secrets.EMAIL_USERNAME }}
#           password: ${{ secrets.EMAIL_PASSWORD }}
#           subject: CI Pipeline Notification
#           body: The CI pipeline for the notification-service-pipelines repository has completed successfully. with "${{ github.event.head_commit.message }}" Please check the SonarCloud and Snyk reports for details. Best regards, Your CI Pipeline
#           to: ${{ secrets.RECIVER_EMAIL }}
#           from: ${{ secrets.EMAIL_USERNAME }}
name: CI Pipeline (Sonar + Snyk + Docker + Trivy)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: notification-service
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
# -------------------------------
# 1. SONAR SCAN + TEST
# -------------------------------
  sonarscan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Run Tests and Generate Coverage
        run: npm test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=notification-service-pipelines
            -Dsonar.organization=muhammedsinanust
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**,coverage/**,**/*.test.js
            -Dsonar.coverage.exclusions=server.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.host.url=https://sonarcloud.io

      - name: Sonar Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        # with:
        #   scanMetadataReportFile: .scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

# -------------------------------
# 2. SNYK SCAN
# -------------------------------
  snykscan:
    name: Snyk Scan
    needs: sonarscan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci --ignore-scripts

      - name: Snyk Test
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

# -------------------------------
# 3. BUILD + DOCKER + TRIVY
# -------------------------------
  build-and-push:
    name: Build Image & Scan
    needs: snykscan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Image Tag
        id: meta
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ steps.meta.outputs.tag }} .
          docker tag $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ steps.meta.outputs.tag }} $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

      # - name: Install Trivy
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y wget apt-transport-https gnupg lsb-release
      #     wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
      #     echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
      #     sudo apt-get update
      #     sudo apt-get install -y trivy
      
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ steps.meta.outputs.tag }}
          severity: HIGH,CRITICAL
          exit-code: '0'
        # run: |
        #   trivy image --severity HIGH,CRITICAL --exit-code 0 \
        #   $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ steps.meta.outputs.tag }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ steps.meta.outputs.tag }}
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

# -------------------------------
# 5. EMAIL NOTIFICATION
# -------------------------------
  mailnotification:
    name: Email Notification
    needs: [sonarscan, snykscan, build-and-push]
    runs-on: ubuntu-latest

    steps:
      - name: Send Failure Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ❌ CI Pipeline Failed
          body: |
            Pipeline FAILED for commit: "${{ github.event.head_commit.message }}"
            Repo: ${{ github.repository }}
            Pipeline Status: ${{ job.status }}
            Check GitHub Actions for logs.
          to: ${{ secrets.RECIVER_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}

      - name: Send Success Email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ✅ CI Pipeline Success
          body: |
            Pipeline SUCCESS for commit: "${{ github.event.head_commit.message }}"
            Docker Image: $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ steps.meta.outputs.tag }}
            Pipeline Status: ${{ job.status }}
            Check details in GitHub Actions.
          to: ${{ secrets.RECIVER_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}
          
          